const colors=[{id:"gray",label:"Gray",fg:"30",bg:"40",hex:"#9CA3AF"},{id:"red",label:"Red",fg:"31",bg:"41",hex:"#F87171"},{id:"yellow",label:"Yellow",fg:"33",bg:"43",hex:"#FACC15"},{id:"green",label:"Green",fg:"32",bg:"42",hex:"#34D399"},{id:"cyan",label:"Cyan",fg:"36",bg:"46",hex:"#22D3EE"},{id:"blue",label:"Blue",fg:"34",bg:"44",hex:"#60A5FA"},{id:"magenta",label:"Magenta",fg:"35",bg:"45",hex:"#F472B6"},{id:"white",label:"White",fg:"37",bg:"47",hex:"#F8FAFC"}];
const faq=[{"q":"How do I make colored text in Discord?","a":"Use an ansi code block in a supported Discord client. Type your message in this generator, select the text you want to style, choose supported ANSI colors or styles, then copy the full fenced ansi block and paste it into Discord."},{"q":"What is a Discord color text generator?","a":"A Discord color text generator creates ANSI-formatted code blocks for Discord. Instead of typing escape codes manually, you choose colors in a visual editor and copy a ready-to-paste block."},{"q":"Does Discord colored text work on mobile?","a":"Mobile support may vary. Discord ANSI colored text generally works best in supported Discord desktop and web clients. Some mobile clients may show plain text or render styles differently."},{"q":"Can I use custom hex colors in Discord text?","a":"No. Discord ANSI text uses a limited palette, not arbitrary hex, RGB, or brand colors. This tool should only offer colors that map to supported ANSI codes."},{"q":"Why is my Discord colored text not working?","a":"Check that you pasted the full ansi code block, including the opening triple backticks, the ansi label, the generated escape sequences, and the closing triple backticks. Rendering can also vary by Discord client and version."},{"q":"What colors work in Discord ANSI code blocks?","a":"Discord ANSI color blocks support a limited set of foreground and background colors based on ANSI codes. The exact labels and preview colors should be verified by development and QA before launch."},{"q":"Is FontGenerators.app affiliated with Discord?","a":"No. FontGenerators.app is an unofficial tool and is not made, endorsed, sponsored, or approved by Discord. Discord is a trademark of its respective owner."},{"q":"Is this Discord colored text generator free?","a":"Yes for the MVP. The tool is planned as a free browser-based utility with no sign-in, checkout, pricing page, Pro plan, or subscription in v0."},{"q":"Does FontGenerators.app save the text I type?","a":"The MVP is designed to generate the ANSI output in your browser and not intentionally store the text you type on FontGenerators.app servers. Do not enter sensitive, confidential, or private information into the tool."}];
const el={msg:document.querySelector('#message'),fg:document.querySelector('#fg-controls'),bg:document.querySelector('#bg-controls'),preview:document.querySelector('#preview'),output:document.querySelector('#output'),status:document.querySelector('#copy-status')};
let spans=[];
let lastText='';
const esc=s=>s.replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[m]));
function addButtons(){colors.forEach(c=>{const b=document.createElement('button');b.type='button';b.innerHTML=`<span class="swatch" style="background:${c.hex}"></span>${c.label}`;b.setAttribute('aria-label',`Apply ${c.label} text color`);b.onclick=()=>apply({foreground:c.id});el.fg.appendChild(b);const bb=document.createElement('button');bb.type='button';bb.innerHTML=`<span class="swatch" style="background:${c.hex}"></span>${c.label}`;bb.setAttribute('aria-label',`Apply ${c.label} background color`);bb.onclick=()=>apply({background:c.id});el.bg.appendChild(bb);});document.querySelector('[data-style="bold"]').onclick=()=>apply({bold:true});document.querySelector('[data-style="underline"]').onclick=()=>apply({underline:true});}
function selected(){const a=el.msg.selectionStart,b=el.msg.selectionEnd;return [Math.min(a,b),Math.max(a,b)]}
function apply(style){const [start,end]=selected();if(start===end){setStatus('Select text first, or choose a style to apply to new text if the editor supports it.');el.msg.focus();return}spans.push({start,end,foreground:null,background:null,bold:false,underline:false,...style});normalize();render();el.msg.focus();}
function normalize(){const len=el.msg.value.length;spans=spans.map(s=>({...s,start:Math.max(0,Math.min(len,s.start)),end:Math.max(0,Math.min(len,s.end))})).filter(s=>s.end>s.start)}
function styleAt(i){const out={foreground:null,background:null,bold:false,underline:false};for(const s of spans){if(i>=s.start&&i<s.end){if(s.foreground)out.foreground=s.foreground;if(s.background)out.background=s.background;if(s.bold)out.bold=true;if(s.underline)out.underline=true}}return out}
function key(st){return [st.foreground||'',st.background||'',st.bold?'b':'',st.underline?'u':''].join('|')}
function ansiCodes(st){const codes=[];if(st.bold)codes.push('1');if(st.underline)codes.push('4');if(st.foreground)codes.push(colors.find(c=>c.id===st.foreground).fg);if(st.background)codes.push(colors.find(c=>c.id===st.background).bg);return codes}
function buildAnsi(){const text=el.msg.value;if(!text)return '```ansi\n\n```';let out='',prev=key({});for(let i=0;i<text.length;i++){const st=styleAt(i),k=key(st);if(k!==prev){if(prev!==key({}))out+='\u001b[0m';const codes=ansiCodes(st);if(codes.length)out+='\u001b['+codes.join(';')+'m';prev=k}out+=text[i]}if(prev!==key({}))out+='\u001b[0m';return '```ansi\n'+out+'\n```'}
function renderPreview(){const text=el.msg.value;if(!text){el.preview.innerHTML='<span class="helper">Type a message before copying your Discord ansi block.</span>';return}let html='',open='';for(let i=0;i<text.length;i++){const st=styleAt(i);const cls=[st.foreground?'fg-'+st.foreground:'',st.background?'bg-'+st.background:'',st.bold?'bold':'',st.underline?'underline':''].filter(Boolean).join(' ');if(cls!==open){if(open)html+='</span>';if(cls)html+=`<span class="${cls}" style="${st.bold?'font-weight:800;':''}${st.underline?'text-decoration:underline;':''}">`;open=cls}html+=text[i]==='\n'?'<br/>':esc(text[i])}if(open)html+='</span>';el.preview.innerHTML=html;}
function render(){normalize();renderPreview();el.output.textContent=buildAnsi();lastText=el.msg.value;}
function setStatus(s){el.status.textContent=s}
document.querySelector('#copy').onclick=async()=>{if(!el.msg.value.trim()){setStatus('Type a message before copying your Discord ansi block.');return}setStatus('Preparing block...');try{await navigator.clipboard.writeText(buildAnsi());setStatus('Copied for Discord.')}catch(e){setStatus('Copy failed. Select the generated block and copy it manually.');el.output.focus();}};
document.querySelector('#clear-selected').onclick=()=>{const [start,end]=selected();if(start===end){setStatus('Select text first, or choose a style to apply to new text if the editor supports it.');return}spans=spans.filter(s=>s.end<=start||s.start>=end);render();setStatus('Clear selected formatting')};
document.querySelector('#clear-all').onclick=()=>{spans=[];render();setStatus('Reset codes are included to help prevent colors from bleeding into the rest of your message.')};
el.msg.addEventListener('input',()=>{ if(el.msg.value!==lastText){ spans=[]; } render(); });el.msg.addEventListener('select',()=>setStatus('Select a word or line, then apply a color or style.'));
function lists(){document.querySelector('#fg-list').innerHTML=colors.map(c=>`<li><span class="swatch" style="background:${c.hex}"></span><strong>${c.label}</strong> — ANSI ${c.fg}</li>`).join('');document.querySelector('#bg-list').innerHTML=colors.map(c=>`<li><span class="swatch" style="background:${c.hex}"></span><strong>${c.label}</strong> — ANSI ${c.bg}</li>`).join('');document.querySelector('#faq-list').innerHTML=faq.map((f,i)=>`<details ${i===0?'open':''}><summary>${esc(f.q)}</summary><p>${esc(f.a)}</p></details>`).join('')}
addButtons();lists();spans=[{start:0,end:11,foreground:'red',background:null,bold:true,underline:false},{start:22,end:26,foreground:'yellow',background:null,bold:false,underline:true},{start:27,end:39,foreground:'cyan',background:null,bold:false,underline:false}];render();
